import { Report } from "../api/reports";

const esc = (v: unknown): string =>
  String(v ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

function buildHtml(report: Report): string {
  const a = report.analysis || {};
  const drivers = (a.axis_scores || []).filter((x) => x.is_driver);
  const fmtRef = (lo: unknown, hi: unknown) =>
    lo == null && hi == null ? "—" : `${lo ?? ""}${lo != null || hi != null ? " – " : ""}${hi ?? ""}`;

  const safety = report.safety_alerts.length
    ? `<h2 class="warn">Safety alerts</h2><ul>${report.safety_alerts
        .map((s: any) => `<li><b>${esc(s.module)}</b> — ${esc(s.reason)} <i>(${esc(s.severity || "review")})</i></li>`)
        .join("")}</ul><p class="muted">Flagged for clinician review — never auto-removed.</p>`
    : "";

  const driverRows = drivers
    .map((ax) => `<tr><td>${esc(ax.axis_code)}</td><td>${esc(ax.axis_name)}</td><td>${esc(ax.severity)}</td></tr>`)
    .join("");

  const moduleRows = report.modules
    .map(
      (m) =>
        `<tr><td>${esc(m.module_code)} ${esc(m.module_name || "")}</td><td>${esc(m.phase || "—")}</td><td>${esc(
          m.dose || "—"
        )}</td><td>${esc(m.clinical_role || "—")}</td></tr>`
    )
    .join("");

  const chain = (a.root_cause_chain?.length ?? 0) > 0
    ? `<p><b>Root-cause chain:</b> ${esc(a.root_cause_chain!.join("  →  "))}</p>` : "";

  const monitoring = report.monitoring.length
    ? `<p class="muted">Reassess: ${esc(report.monitoring.map((mo: any) => JSON.stringify(mo.reassess_every_days ?? mo)).join(", "))}</p>`
    : "";

  const note = report.doctor_note ? `<p><b>Doctor note:</b> ${esc(report.doctor_note)}</p>` : "";

  return `<!doctype html><html><head><meta charset="utf-8"><title>TSPI Treatment Plan — ${esc(report.case_id)}</title>
  <style>
    @page { margin: 18mm; }
    body { font-family: Arial, Helvetica, sans-serif; color:#1f2933; font-size:12px; line-height:1.45; }
    h1 { font-size:20px; margin:0 0 2px; } h2 { font-size:14px; margin:18px 0 6px; border-bottom:1px solid #ddd; padding-bottom:3px; }
    h2.warn { color:#b91c1c; border-color:#fecaca; }
    .meta { color:#6b7280; font-size:11px; margin-bottom:10px; }
    table { width:100%; border-collapse:collapse; margin:6px 0; }
    th,td { border:1px solid #e5e7eb; padding:5px 8px; text-align:left; font-size:11px; }
    th { background:#f3f4f6; }
    .muted { color:#6b7280; }
    .nss { font-size:16px; font-weight:bold; }
    pre { white-space:pre-wrap; background:#f8fafc; border:1px solid #eee; padding:10px; border-radius:6px; font-size:11px; }
    .disclaimer { margin-top:16px; color:#6b7280; font-style:italic; font-size:10px; border-top:1px solid #ddd; padding-top:8px; }
  </style></head><body>
    <h1>TSPI Treatment Plan</h1>
    <div class="meta">Case ${esc(report.case_id)}${report.tspi_report_id ? ` · TSPI ${esc(report.tspi_report_id)}` : ""}
      · Status: ${esc(report.status)} ${report.deliverable ? "(deliverable)" : "(draft)"} · Generated ${esc(new Date(report.created_at).toLocaleString())}</div>
    <p class="nss">NSS ${esc(report.nss)} — Level ${esc(report.severity_level)} (${esc(report.severity_name || "—")})</p>
    ${safety}
    ${driverRows ? `<h2>Root-cause drivers</h2><table><thead><tr><th>Axis</th><th>Name</th><th>Severity</th></tr></thead><tbody>${driverRows}</tbody></table>` : ""}
    ${chain}
    <h2>Module plan (dosed &amp; sequenced)</h2>
    <table><thead><tr><th>Module</th><th>Phase</th><th>Dose</th><th>Role</th></tr></thead><tbody>${moduleRows || '<tr><td colspan="4">No modules.</td></tr>'}</tbody></table>
    ${monitoring}
    ${note}
    <h2>Full report</h2>
    <pre>${esc(report.report_markdown || "(no narrative)")}</pre>
    <div class="disclaimer">${esc(report.disclaimer || "For clinician review and approval — not a substitute for medical judgment.")}<br/>Generated by MiHealth Portal on ${esc(new Date().toLocaleString())}.</div>
  </body></html>`;
}

// Renders the report into a hidden iframe and opens the print dialog (choose "Save as PDF").
export function printReportPdf(report: Report): void {
  const iframe = document.createElement("iframe");
  iframe.style.cssText = "position:fixed;right:0;bottom:0;width:0;height:0;border:0;";
  document.body.appendChild(iframe);
  const doc = iframe.contentWindow?.document;
  if (!doc) return;
  doc.open();
  doc.write(buildHtml(report));
  doc.close();
  const win = iframe.contentWindow!;
  win.focus();
  setTimeout(() => {
    win.print();
    setTimeout(() => document.body.removeChild(iframe), 1500);
  }, 350);
}
